version: '3'
services:
        homeassistant:
                container_name: homeassistant
                image: homeassistant/raspberrypi4-homeassistant:stable
                volumes:
                        - /home/homeassistant/config:/config
                        - /etc/localtime:/etc/localtime:ro
                restart: unless-stopped
                network_mode: host
                devices:
                        - /dev/ttyS0:/dev/ttyS0
